#ifndef DECISION_H
#define DECISION_H

#include <map>
#include <string>
#include <vector>

namespace decision {

struct node {
    std::map<std::string, std::string> values;
    bool positive;
};

// Tokenizes a string and returns it as a vector of strings.
// 'str' the string being tokenized
// 'delim' the delimiter by which to split the string
// Returns a vector that contains the tokens of the string.
std::vector<std::string> string_to_tokens(const std::string& str, char delim);

// Given a filepath, reads all lines from the file and creates a node from each.
// 'filepath' the filepath to the data file that contains node information
// Returns a vector that contains all nodes created from the data file.
std::vector<node> read_nodes_from_filepath(const std::string& filepath);

// Computes the entropy for a given set based on a value.
// 'data' must be non-NULL and is a vector containing all nodes.
// 'value' is the value on which entropy is being computed.
// Returns a double which represents the entropy of the set.
double entropy(const std::vector<node>& data, const std::string& value);

// Computes the entropy of a subset (split by a value) of a given set of data.
// 'data' must be non-NULL and is a vector containing all nodes.
// 'key' is the key in which we are searching for the value.
// 'split_value' is the value by which the set is being split.
// 'tar_val' is the target value for the decision tree.
// Returns a double which represents the entropy of the subset generated by
// splitting the set on a value.
double subset_entropy(const std::vector<node>& data,
                      const std::string& value,
                      const std::string& split_value,
                      const std::string& tar_val);

// Computes the information gained from splitting the data set on a specific
// value.
// 'data' must be non-NULL and is a vector containing all nodes.
// 'split_value' is the value by which the set is being split.
// 'tar_val' is the target value for the decision tree.
// Returns a double which represents the difference in current entropy and the
// entropy from splitting the set.
double info_gain(const std::vector<node>& data,
                 const std::string& split_value,
                 const std::string& tar_val);

// Counts how many times each value appears for a given key in the list of
// nodes.
// 'data' must be non-NULL and is a vector containing all nodes.
// 'key' is the key whose values are being counted.
// Returns a map with <value, count> pairings.
std::map<std::string, int> count_occurrences(
        const std::vector<node>& data, const std::string& key);

// Computes the log (base 2) of a given value.
// 'x' is the value for which the log is being computed.
// Returns the log (base 2) of x.
double lg(double x);

}  // namespace decision

#endif  // DECISION_H
